#!/usr/bin/env python3
"""Emit a semantic membership bridge into the selected-prefix cover.

The bridge proves that the existing graph-accepted trace-margin surface lands
inside the generated selected-prefix cover.  This is still not final global
coverage, but it checks that the new prefix-cover root can subsume the older
accepted-trace/margin socket without sampled rank/path objects.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import emit_top_pairing_state_dag_selected_prefix_group as group_emit


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_COVER = ROOT / "scripts/generated/top_pairing_shared_gain_prefix_cover_plan.json"
DEFAULT_ACCEPTED = (
    ROOT / "scripts/generated/top_pairing_closed_graph_acceptance_all_examples_lean_aligned.json"
)
DEFAULT_LEAN = (
    ROOT
    / "Cuboctahedron/Generated/NonIdentity/Residual/"
    / "BellmanTopPairingSelectedPrefixCoverMembershipBridge.lean"
)
DEFAULT_JSON = (
    ROOT / "scripts/generated/top_pairing_selected_prefix_cover_membership_bridge.json"
)
DEFAULT_MD = (
    ROOT / "scripts/generated/top_pairing_selected_prefix_cover_membership_bridge.md"
)


def nested_or_wrap(index: int, count: int, proof: str) -> str:
    if count == 1:
        return proof
    if index == 0:
        return f"Or.inl ({proof})"
    return f"Or.inr ({nested_or_wrap(index - 1, count - 1, proof)})"


def bucket_proof_name(bucket_idx: int) -> tuple[str, str]:
    group_idx = bucket_idx // 5
    local_idx = bucket_idx % 5
    return f"Group{group_idx:03d}", f"Prefix{local_idx:03d}"


def render_bridge(cover: dict[str, Any], accepted: list[dict[str, Any]]) -> str:
    id_to_bucket: dict[int, int] = {}
    for bucket_idx, bucket in enumerate(cover["cover"]):
        for trace_id in bucket["accepted_indices"]:
            id_to_bucket[trace_id] = bucket_idx

    if sorted(id_to_bucket) != list(range(len(accepted))):
        raise RuntimeError("cover does not map exactly the accepted trace ids")

    group_count = (len(cover["cover"]) + 4) // 5
    lines = [
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixCoverSocket",
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphAcceptedTraceMarginBridge",
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTerminalAcceptedBridge",
        "",
        "/-!",
        "Membership bridge from the graph-accepted trace-margin surface into",
        "the selected-prefix Bellman cover.",
        "",
        "Generated by",
        "`scripts/emit_top_pairing_selected_prefix_cover_membership_bridge.py`.",
        "No sampled rank/path objects are introduced.",
        "-/",
        "",
        "set_option linter.unnecessarySimpa false",
        "",
        "namespace Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixCoverMembershipBridge",
        "",
        "open Cuboctahedron",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphAcceptedEvalGate",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphAcceptedTraceMarginBridge",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTerminalAcceptedBridge",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphEvalSplit10MSmoke.Base",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixCoverSocket",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingStateDAGSelectedPrefixCover",
        "",
        "theorem selectedPrefixCoverFamily_of_graphAcceptedTraceMargin",
        "    {scaledMargin : Fin numPairWords -> Int}",
        "    {rank : Fin numPairWords}",
        "    (hclosed : TopPairingClosedLanguageAtRank rank Face.ym)",
        "    (hactual : TopPairingActualFaceOmniAtRank rank)",
        "    (hbad :",
        "      Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphAcceptedEvalLanguage.AcceptedSequenceBadFaceAtRank",
        "        rank Face.ym)",
        "    (hterm :",
        "      TopPairingTraceClassifier.TerminalOk.TerminalTraceLabels",
        "        (topPairingRankFaceLabels rank))",
        "    (hgraph :",
        "      Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphAcceptedEvalGate.GraphAcceptedTraceMargin scaledMargin",
        "        ({ rank := rank, closed := hclosed } : TopPairingBellmanObj Face.ym)) :",
        "    SelectedPrefixCoverFamily scaledMargin rank := by",
        "  rcases graphAcceptedTraceMarginIdBound_of_graphAcceptedTraceMargin hgraph with",
        "    ⟨id, htrace, hmargin⟩",
        "  cases id",
    ]

    for trace_id, item in enumerate(accepted):
        bucket_idx = id_to_bucket[trace_id]
        group_name, prefix_name = bucket_proof_name(bucket_idx)
        bucket = cover["cover"][bucket_idx]
        bucket_count = min(5, len(cover["cover"]) - (bucket_idx // 5) * 5)
        local_idx = bucket_idx % 5
        rest = item["labels"][len(bucket["prefix"]) :]
        rest_expr = group_emit.face_expr(rest)
        prefix_exists = (
            f"⟨{rest_expr}, by "
            f"simpa [hlabels, acceptedTraceOfId, acceptedFaceTrace_{trace_id:03d}, "
            f"{group_name}.{prefix_name}Prefix]⟩"
        )
        hbucket = (
            f"⟨hclosed, hactual, hbad, hterm, {prefix_exists}, "
            "by simpa [acceptedTraceGain] using hmargin⟩"
        )
        hgroup = nested_or_wrap(local_idx, bucket_count, hbucket)
        hcover = nested_or_wrap(bucket_idx // 5, group_count, hgroup)
        lines.extend(
            [
                "  · have hlabels :",
                f"      topPairingRankFaceLabels rank = acceptedTraceOfId AcceptedTraceId.t{trace_id:03d} := by",
                "      simpa [TopPairingBellmanObj.labels, TopPairingBellmanObj.forcedSeq,",
                "        topPairingRankFaceLabels] using htrace",
                f"    exact {hcover}",
            ]
        )

    lines.extend(
        [
            "",
            "theorem selectedPrefixCoverSequenceBadFace_of_terminalAcceptedEval",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (h :",
            "      TopPairingStrengthenedClosedLanguageAtRank",
            "        (TerminalAcceptedEvalSequenceBadFace scaledMargin) rank Face.ym) :",
            "    SelectedPrefixCoverSequenceBadFace scaledMargin rank Face.ym := by",
            "  rcases h.sequenceBadFace_ok with ⟨hbad, hterm, hclosed, hgraph⟩",
            "  exact ⟨rfl,",
            "    selectedPrefixCoverFamily_of_graphAcceptedTraceMargin",
            "      hclosed h.actualFaceOmni hbad hterm hgraph⟩",
            "",
            "theorem selectedPrefixCover_evalLanguage_of_terminalAcceptedEval",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (h :",
            "      TopPairingStrengthenedClosedLanguageAtRank",
            "        (TerminalAcceptedEvalSequenceBadFace scaledMargin) rank Face.ym) :",
            "    TopPairingBellmanEvalLanguageAtRank",
            "      graphPotential graphSmokeNext smokeLabelOfFace rootState (176 : Int)",
            "      scaledMargin rank Face.ym := by",
            "  exact evalLanguage_of_strengthenedSelectedPrefixCover",
            "    (TopPairingStrengthenedClosedLanguageAtRank.ofComponents",
            "      h.closed h.actualFaceOmni",
            "      (selectedPrefixCoverSequenceBadFace_of_terminalAcceptedEval h))",
            "",
            "theorem selectedPrefixCover_scaledMargin_nonpos_of_terminalAcceptedEval",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (h :",
            "      TopPairingStrengthenedClosedLanguageAtRank",
            "        (TerminalAcceptedEvalSequenceBadFace scaledMargin) rank Face.ym) :",
            "    scaledMargin rank <= 0 := by",
            "  exact strengthenedSelectedPrefixCover_scaledMargin_nonpos",
            "    (TopPairingStrengthenedClosedLanguageAtRank.ofComponents",
            "      h.closed h.actualFaceOmni",
            "      (selectedPrefixCoverSequenceBadFace_of_terminalAcceptedEval h))",
            "",
            "theorem selected_prefix_cover_membership_bridge_builds : True := by",
            "  exact True.intro",
            "",
            "end Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixCoverMembershipBridge",
            "",
        ]
    )
    return "\n".join(lines)


def render_markdown(report: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Top-Pairing Selected Prefix Cover Membership Bridge",
            "",
            "This generated bridge maps each graph-accepted trace id to the",
            "selected-prefix cover bucket that contains it.",
            "",
            f"- accepted trace ids: `{report['accepted_trace_count']}`",
            f"- cover buckets: `{report['bucket_count']}`",
            f"- Lean file: `{report['lean_file']}`",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cover-json", type=Path, default=DEFAULT_COVER)
    parser.add_argument("--accepted-json", type=Path, default=DEFAULT_ACCEPTED)
    parser.add_argument("--lean", type=Path, default=DEFAULT_LEAN)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MD)
    args = parser.parse_args()

    cover = json.loads(args.cover_json.read_text())
    accepted = json.loads(args.accepted_json.read_text())["first_accepted"]

    args.lean.parent.mkdir(parents=True, exist_ok=True)
    args.lean.write_text(render_bridge(cover, accepted))

    report = {
        "accepted_trace_count": len(accepted),
        "bucket_count": len(cover["cover"]),
        "lean_file": args.lean.relative_to(ROOT).as_posix(),
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    args.markdown.write_text(render_markdown(report))


if __name__ == "__main__":
    main()
