#!/usr/bin/env python3
"""Emit the full bounded selected-prefix cover for top-pairing Bellman.

The cover is still only the current top-pairing Bellman subproblem, not the
whole cuboctahedron proof.  It is useful because it checks the next scaling
gate: all shared-gain prefix buckets are assembled through semantic group
modules and a small root theorem, without sampled rank/path objects.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import emit_top_pairing_state_dag_selected_prefix_group as group_emit


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_COVER = ROOT / "scripts/generated/top_pairing_shared_gain_prefix_cover_plan.json"
DEFAULT_DIR = (
    ROOT
    / "Cuboctahedron/Generated/NonIdentity/Residual/"
    / "BellmanTopPairingStateDAGSelectedPrefixCover"
)
DEFAULT_JSON = ROOT / "scripts/generated/top_pairing_state_dag_selected_prefix_cover.json"
DEFAULT_MD = ROOT / "scripts/generated/top_pairing_state_dag_selected_prefix_cover.md"
ROOT_NAMESPACE = (
    "Cuboctahedron.Generated.NonIdentity.Residual."
    "BellmanTopPairingStateDAGSelectedPrefixCover"
)
ROOT_IMPORT = (
    "Cuboctahedron.Generated.NonIdentity.Residual."
    "BellmanTopPairingStateDAGSelectedPrefixCover"
)


def module_import(group_idx: int) -> str:
    return f"{ROOT_IMPORT}.Group{group_idx:03d}"


def group_namespace(group_idx: int) -> str:
    return f"{ROOT_NAMESPACE}.Group{group_idx:03d}"


def nested_or_type(groups: list[str], scaled: str, rank: str) -> str:
    terms = [f"{group}.SelectedPrefixGroupFamily {scaled} {rank}" for group in groups]
    if len(terms) == 1:
        return terms[0]
    return " \\/\n    ".join(terms)


def emit_or_cases(groups: list[str], theorem_name: str) -> list[str]:
    lines = ["  rcases hrank with " + " | ".join(f"h{i}" for i in range(len(groups)))]
    for i, group in enumerate(groups):
        lines.append(f"  · exact {group}.{theorem_name} h{i}")
    return lines


def render_root(group_count: int) -> str:
    groups = [f"Group{i:03d}" for i in range(group_count)]
    lines = [f"import {module_import(i)}" for i in range(group_count)]
    lines.extend(
        [
            "",
            "/-!",
            "Root for the bounded selected-prefix top-pairing Bellman cover.",
            "",
            "Generated by `scripts/emit_top_pairing_state_dag_selected_prefix_cover.py`.",
            "This root imports bounded semantic group modules and composes only",
            "their small theorem surfaces.",
            "-/",
            "",
            f"namespace {ROOT_NAMESPACE}",
            "",
            "open Cuboctahedron",
            "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphEvalSplit10MSmoke.Base",
            "",
            "def SelectedPrefixCoverFamily",
            "    (scaledMargin : Fin numPairWords -> Int)",
            "    (rank : Fin numPairWords) : Prop :=",
            "  " + nested_or_type(groups, "scaledMargin", "rank"),
            "",
            "theorem selectedPrefixCover_evalLanguage",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixCoverFamily scaledMargin rank) :",
            "    TopPairingBellmanEvalLanguageAtRank",
            "      graphPotential graphSmokeNext smokeLabelOfFace rootState (176 : Int)",
            "      scaledMargin rank Face.ym := by",
            *emit_or_cases(groups, "selectedPrefixGroup_evalLanguage"),
            "",
            "theorem selectedPrefixCover_scaledMargin_nonpos",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixCoverFamily scaledMargin rank) :",
            "    scaledMargin rank <= 0 := by",
            *emit_or_cases(groups, "selectedPrefixGroup_scaledMargin_nonpos"),
            "",
            "theorem selected_prefix_cover_builds : True := by",
            "  exact True.intro",
            "",
            f"end {ROOT_NAMESPACE}",
            "",
        ]
    )
    return "\n".join(lines)


def render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Top-Pairing Selected Prefix Cover",
        "",
        "This is generated scaffolding plus exact diagnostic planning data, not",
        "standalone proof.  The corresponding Lean root composes bounded group",
        "modules for every selected shared-gain prefix bucket.",
        "",
        f"- source cover: `{report['source_cover']}`",
        f"- bucket count: `{report['bucket_count']}`",
        f"- group size: `{report['group_size']}`",
        f"- group count: `{report['group_count']}`",
        f"- accepted traces covered: `{report['accepted_trace_count']}`",
        f"- root Lean file: `{report['root_lean_file']}`",
        "",
        "## Groups",
        "",
        "| group | buckets | accepted traces | Lean file |",
        "| ---: | --- | ---: | --- |",
    ]
    for group in report["groups"]:
        lines.append(
            "| `{index}` | `{start}`-`{end}` | `{accepted}` | `{lean}` |".format(
                index=group["index"],
                start=group["bucket_start"],
                end=group["bucket_end"] - 1,
                accepted=group["accepted_trace_count"],
                lean=group["lean_file"],
            )
        )
    lines.extend(
        [
            "",
            "## Gate",
            "",
            "Accept the full selected-prefix cover only if `All.lean` builds under a",
            "guarded focused check and forbidden-token scans show no sampled",
            "membership or forbidden proof shortcuts.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cover-json", type=Path, default=DEFAULT_COVER)
    parser.add_argument("--group-size", type=int, default=5)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_DIR)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MD)
    args = parser.parse_args()

    if args.group_size <= 0:
        raise SystemExit("--group-size must be positive")

    cover = json.loads(args.cover_json.read_text())
    buckets = list(cover["cover"])
    group_count = math.ceil(len(buckets) / args.group_size)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    groups = []
    accepted_all = set()
    for group_idx in range(group_count):
        start = group_idx * args.group_size
        end = min(start + args.group_size, len(buckets))
        group_buckets = buckets[start:end]
        accepted = {idx for bucket in group_buckets for idx in bucket["accepted_indices"]}
        accepted_all.update(accepted)
        lean_path = args.out_dir / f"Group{group_idx:03d}.lean"
        lean_path.write_text(
            group_emit.render_lean(
                group_buckets,
                namespace=group_namespace(group_idx),
            )
        )
        groups.append(
            {
                "index": group_idx,
                "bucket_start": start,
                "bucket_end": end,
                "bucket_count": len(group_buckets),
                "accepted_trace_count": len(accepted),
                "lean_file": lean_path.relative_to(ROOT).as_posix(),
            }
        )

    root_path = args.out_dir / "All.lean"
    root_path.write_text(render_root(group_count))

    report = {
        "source_cover": args.cover_json.relative_to(ROOT).as_posix(),
        "bucket_count": len(buckets),
        "group_size": args.group_size,
        "group_count": group_count,
        "accepted_trace_count": len(accepted_all),
        "root_lean_file": root_path.relative_to(ROOT).as_posix(),
        "groups": groups,
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    args.markdown.write_text(render_markdown(report))


if __name__ == "__main__":
    main()
