#!/usr/bin/env python3
"""Emit the selected-prefix trace-margin killed bridge.

This is the final small theorem-facing adapter for the current top-pairing
Bellman trace-id experiment.  The input family is already semantic:
`SelectedPrefixTraceMarginFamily` is a disjunction of terminal prefix/shared-gain
families.  This emitter maps each disjunct to the trace-id start-violation killed
bridge using the generated prefix/gain theorem from the corresponding
selected-prefix group.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_COVER = ROOT / "scripts/generated/top_pairing_shared_gain_prefix_cover_plan.json"
DEFAULT_LEAN = (
    ROOT
    / "Cuboctahedron/Generated/NonIdentity/Residual/"
    / "BellmanTopPairingSelectedPrefixTraceStartViolationKilledBridge.lean"
)
DEFAULT_JSON = (
    ROOT
    / "scripts/generated/"
    / "top_pairing_selected_prefix_trace_start_violation_killed_bridge.json"
)
DEFAULT_MD = (
    ROOT
    / "scripts/generated/"
    / "top_pairing_selected_prefix_trace_start_violation_killed_bridge.md"
)


def group_name(bucket_idx: int) -> str:
    return f"Group{bucket_idx // 5:03d}"


def prefix_name(bucket_idx: int) -> str:
    return f"Prefix{bucket_idx % 5:03d}"


def render_lean(cover: dict[str, Any]) -> str:
    buckets = list(cover["cover"])
    lines = [
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginAdapter",
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginCoverBridge",
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTraceStartViolationKilledBridge",
        "",
        "/-!",
        "Killed bridge for the selected-prefix trace-margin family.",
        "",
        "Generated by",
        "`scripts/emit_top_pairing_selected_prefix_trace_start_violation_killed_bridge.py`.",
        "",
        "The input family is semantic: it is a disjunction of terminal",
        "prefix/shared-gain families, not sampled rank or sampled path evidence.",
        "Each terminal prefix supplies an accepted-trace-id bucket and shared gain;",
        "the all-trace start-violation provider root then turns the Bellman",
        "nonpositive margin into `Coverage.NonIdentityRankKilled`.",
        "-/",
        "",
        "set_option maxHeartbeats 2000000",
        "set_option maxRecDepth 4096",
        "",
        "namespace Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceStartViolationKilledBridge",
        "",
        "open Cuboctahedron",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingStateDAGSelectedPrefixCover",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginAdapter",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginCoverBridge",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTraceStartViolationKilledBridge",
        "",
        "theorem nonIdentityRankKilled_of_selectedPrefixTraceMarginFamily",
        "    {scaledMargin : Fin numPairWords -> Int}",
        "    {rank : Fin numPairWords}",
        "    (hrank : SelectedPrefixTraceMarginFamily scaledMargin rank) :",
        "    Cuboctahedron.Generated.Coverage.NonIdentityRankKilled rank := by",
        "  unfold SelectedPrefixTraceMarginFamily at hrank",
        "  rcases hrank with "
        + " | ".join(f"h{i}" for i in range(len(buckets))),
    ]
    for idx, bucket in enumerate(buckets):
        group = group_name(idx)
        prefix = prefix_name(idx)
        gain = int(bucket["gain"])
        lines.extend(
            [
                "  · exact",
                "      nonIdentityRankKilled_of_terminalTracePrefixSharedGainClosedMarginFamily",
                f"        (allowedTraceId := {group}.{prefix}Allowed)",
                f"        (pfx := {group}.{prefix}Prefix)",
                f"        (gain := ({gain} : Int))",
                f"        {group}.{prefix}Prefix_gain",
                f"        h{idx}",
            ]
        )

    lines.extend(
        [
            "",
            "theorem nonIdentityRankKilled_of_selectedPrefixCoverFamily",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixCoverFamily scaledMargin rank) :",
            "    Cuboctahedron.Generated.Coverage.NonIdentityRankKilled rank :=",
            "  nonIdentityRankKilled_of_selectedPrefixTraceMarginFamily",
            "    (selectedPrefixTraceMarginFamily_of_selectedPrefixCoverFamily hrank)",
            "",
            "theorem selected_prefix_trace_start_violation_killed_bridge_builds : True := by",
            "  exact True.intro",
            "",
            "end Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceStartViolationKilledBridge",
            "",
        ]
    )
    return "\n".join(lines)


def render_markdown(report: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Top-Pairing Selected Prefix Trace Start-Violation Killed Bridge",
            "",
            "This generated bridge maps the semantic selected-prefix trace-margin",
            "family to `Coverage.NonIdentityRankKilled` using the accepted trace-id",
            "start-violation providers.",
            "",
            f"- source cover: `{report['source_cover']}`",
            f"- prefix buckets: `{report['bucket_count']}`",
            f"- Lean file: `{report['lean_file']}`",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cover-json", type=Path, default=DEFAULT_COVER)
    parser.add_argument("--lean", type=Path, default=DEFAULT_LEAN)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MD)
    args = parser.parse_args()

    cover = json.loads(args.cover_json.read_text())
    args.lean.parent.mkdir(parents=True, exist_ok=True)
    args.lean.write_text(render_lean(cover))

    report = {
        "source_cover": args.cover_json.relative_to(ROOT).as_posix(),
        "bucket_count": len(cover["cover"]),
        "lean_file": args.lean.relative_to(ROOT).as_posix(),
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    args.markdown.write_text(render_markdown(report))


if __name__ == "__main__":
    main()
