#!/usr/bin/env python3
"""Emit the selected-prefix trace-margin to root-producer bridge.

The source family is generated as an OR over terminal prefix/shared-gain
families.  This emitter keeps the next bridge mechanical and auditable: each
prefix gets a tiny shared-gain theorem, then the root producer theorem simply
case-splits over the existing family.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = (
    ROOT
    / "Cuboctahedron/Generated/NonIdentity/Residual/"
    / "BellmanTopPairingSelectedPrefixTraceMarginAdapter.lean"
)
OUT = (
    ROOT
    / "Cuboctahedron/Generated/NonIdentity/Residual/"
    / "BellmanTopPairingSelectedPrefixTraceMarginRootProducerBridge.lean"
)


ENTRY_RE = re.compile(
    r"TerminalTracePrefixSharedGainClosedMarginFamily "
    r"(?P<prefix>Group\d+\.Prefix\d+Prefix) "
    r"\((?P<gain>-[0-9]+) : Int\) scaledMargin rank"
)


def parse_entries() -> list[tuple[str, int]]:
    text = SRC.read_text()
    entries: list[tuple[str, int]] = []
    in_def = False
    for line in text.splitlines():
        if line.startswith("def SelectedPrefixTraceMarginFamily"):
            in_def = True
        if not in_def:
            continue
        match = ENTRY_RE.search(line)
        if match:
            entries.append((match.group("prefix"), int(match.group("gain"))))
        elif entries and line.startswith("theorem "):
            break
    if not entries:
        raise SystemExit("no SelectedPrefixTraceMarginFamily entries found")
    return entries


def theorem_name(index: int) -> str:
    return f"selectedPrefixTraceMarginPrefix_{index:03d}_gain"


def render(entries: list[tuple[str, int]]) -> str:
    lines: list[str] = [
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginAdapter",
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTraceMarginRootProducerBridge",
        "",
        "/-!",
        "Selected-prefix trace-margin families as root trace-margin producers.",
        "",
        "Generated by",
        "`scripts/emit_top_pairing_selected_prefix_trace_margin_root_producer_bridge.py`.",
        "No sampled rank/path objects are introduced.",
        "-/",
        "",
        "namespace Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginRootProducerBridge",
        "",
        "open Cuboctahedron",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingAcceptedPrefixEvalRoot",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphAcceptedTraceMarginBridge",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginAdapter",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingStateDAGSelectedPrefixCover",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTraceMarginRootProducerBridge",
        "",
    ]

    for index, (prefix, gain) in enumerate(entries):
        name = theorem_name(index)
        lines.extend(
            [
                f"private theorem {name}",
                "    (traceId : AcceptedTraceId)",
                "    (hprefix :",
                f"      (acceptedTraceOfId traceId).take {prefix}.length =",
                f"        {prefix}) :",
                "    (fun traceId : AcceptedTraceId =>",
                f"      (acceptedTraceOfId traceId).take {prefix}.length =",
                f"        {prefix}) traceId /\\",
                f"      acceptedTraceGain traceId = ({gain} : Int) := by",
                "  refine ⟨hprefix, ?_⟩",
                "  cases traceId <;>",
                "    first | rfl | (exfalso; revert hprefix; decide)",
                "",
            ]
        )

    lines.extend(
        [
            "theorem rootTraceMarginProducer_of_selectedPrefixTraceMarginFamily",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixTraceMarginFamily scaledMargin rank) :",
            "    RootTraceMarginProducer scaledMargin rank := by",
            "  unfold SelectedPrefixTraceMarginFamily at hrank",
            "  rcases hrank with "
            + " | ".join(f"h{index}" for index in range(len(entries))),
        ]
    )
    for index, (prefix, gain) in enumerate(entries):
        lines.extend(
            [
                f"  · exact rootTraceMarginProducer_of_terminalTracePrefixSharedGainClosedMarginFamily",
                "      (allowedTraceId := fun traceId : AcceptedTraceId =>",
                f"        (acceptedTraceOfId traceId).take {prefix}.length = {prefix})",
                f"      (pfx := {prefix})",
                f"      (gain := ({gain} : Int))",
                f"      {theorem_name(index)}",
                f"      h{index}",
            ]
        )

    lines.extend(
        [
            "",
            "theorem selected_prefix_trace_margin_root_producer_bridge_builds : True := by",
            "  exact True.intro",
            "",
            "end Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginRootProducerBridge",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    entries = parse_entries()
    OUT.write_text(render(entries))
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"entries={len(entries)}")


if __name__ == "__main__":
    main()
