#!/usr/bin/env python3
"""Emit a semantic bridge from selected-prefix cover to trace-margin socket.

The selected-prefix cover is already a bounded semantic family over state-DAG
prefix shards.  The newer trace-margin socket wants membership in the
trace-margin prefix/gain family.  This bridge proves that every selected-prefix
cover member also belongs to that trace-margin family, without introducing
sampled rank/path objects.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_COVER = ROOT / "scripts/generated/top_pairing_state_dag_selected_prefix_cover.json"
DEFAULT_LEAN = (
    ROOT
    / "Cuboctahedron/Generated/NonIdentity/Residual/"
    / "BellmanTopPairingSelectedPrefixTraceMarginCoverBridge.lean"
)
DEFAULT_JSON = (
    ROOT / "scripts/generated/top_pairing_selected_prefix_trace_margin_cover_bridge.json"
)
DEFAULT_MD = (
    ROOT / "scripts/generated/top_pairing_selected_prefix_trace_margin_cover_bridge.md"
)


def group_name(group_idx: int) -> str:
    return f"Group{group_idx:03d}"


def prefix_name(local_idx: int) -> str:
    return f"Prefix{local_idx:03d}"


def nested_or_wrap(index: int, count: int, proof: str) -> str:
    if count == 1:
        return proof
    if index == 0:
        return f"Or.inl ({proof})"
    return f"Or.inr ({nested_or_wrap(index - 1, count - 1, proof)})"


def render_lean(report: dict[str, Any]) -> str:
    groups = list(report["groups"])
    bucket_count = int(report["bucket_count"])

    lines: list[str] = [
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginSocket",
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixCoverSocket",
        "",
        "/-!",
        "Bridge from the selected-prefix cover family into the selected-prefix",
        "trace-margin socket.",
        "",
        "Generated by",
        "`scripts/emit_top_pairing_selected_prefix_trace_margin_cover_bridge.py`.",
        "No sampled rank/path objects are introduced.",
        "-/",
        "",
        "namespace Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginCoverBridge",
        "",
        "open Cuboctahedron",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphEvalSplit10MSmoke.Base",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingStateDAGPrefixSmoke",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingStateDAGSelectedPrefixCover",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixCoverSocket",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginAdapter",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginSocket",
        "",
    ]

    for group in groups:
        gidx = int(group["index"])
        gname = group_name(gidx)
        start = int(group["bucket_start"])
        end = int(group["bucket_end"])
        for global_idx in range(start, end):
            local_idx = global_idx - start
            pname = prefix_name(local_idx)
            proof = (
                "terminalPrefixFamily_of_stateDAGPrefixFamily "
                f"({gname}.stateDAGPrefixFamily_of_{pname}ShardFamily hrank)"
            )
            injected = nested_or_wrap(global_idx, bucket_count, proof)
            lines.extend(
                [
                    f"theorem selectedPrefixTraceMarginFamily_of_{gname}_{pname}ShardFamily",
                    "    {scaledMargin : Fin numPairWords -> Int}",
                    "    {rank : Fin numPairWords}",
                    f"    (hrank : {gname}.{pname}ShardFamily scaledMargin rank) :",
                    "    SelectedPrefixTraceMarginFamily scaledMargin rank := by",
                    "  unfold SelectedPrefixTraceMarginFamily",
                    f"  exact {injected}",
                    "",
                ]
            )

        local_count = end - start
        theorem_name = f"selectedPrefixTraceMarginFamily_of_{gname}SelectedPrefixGroupFamily"
        lines.extend(
            [
                f"theorem {theorem_name}",
                "    {scaledMargin : Fin numPairWords -> Int}",
                "    {rank : Fin numPairWords}",
                f"    (hrank : {gname}.SelectedPrefixGroupFamily scaledMargin rank) :",
                "    SelectedPrefixTraceMarginFamily scaledMargin rank := by",
                f"  unfold {gname}.SelectedPrefixGroupFamily at hrank",
            ]
        )
        if local_count == 1:
            lines.append(
                f"  exact selectedPrefixTraceMarginFamily_of_{gname}_Prefix000ShardFamily hrank"
            )
        else:
            lines.append(
                "  rcases hrank with "
                + " | ".join(f"h{i}" for i in range(local_count))
            )
            for local_idx in range(local_count):
                pname = prefix_name(local_idx)
                lines.append(
                    f"  · exact selectedPrefixTraceMarginFamily_of_{gname}_{pname}ShardFamily h{local_idx}"
                )
        lines.append("")

    lines.extend(
        [
            "theorem selectedPrefixTraceMarginFamily_of_selectedPrefixCoverFamily",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixCoverFamily scaledMargin rank) :",
            "    SelectedPrefixTraceMarginFamily scaledMargin rank := by",
            "  unfold SelectedPrefixCoverFamily at hrank",
            "  rcases hrank with "
            + " | ".join(f"h{i}" for i in range(len(groups))),
        ]
    )
    for group in groups:
        gidx = int(group["index"])
        gname = group_name(gidx)
        lines.append(
            f"  · exact selectedPrefixTraceMarginFamily_of_{gname}SelectedPrefixGroupFamily h{gidx}"
        )
    lines.extend(
        [
            "",
            "theorem selectedPrefixTraceMarginSequenceBadFace_of_selectedPrefixCoverFamily",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixCoverFamily scaledMargin rank) :",
            "    SelectedPrefixTraceMarginSequenceBadFace scaledMargin rank Face.ym := by",
            "  exact ⟨rfl, selectedPrefixTraceMarginFamily_of_selectedPrefixCoverFamily hrank⟩",
            "",
            "theorem strengthenedTraceMargin_of_strengthenedSelectedPrefixCover",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (h :",
            "      TopPairingStrengthenedClosedLanguageAtRank",
            "        (SelectedPrefixCoverSequenceBadFace scaledMargin) rank Face.ym) :",
            "    TopPairingStrengthenedClosedLanguageAtRank",
            "      (SelectedPrefixTraceMarginSequenceBadFace scaledMargin) rank Face.ym := by",
            "  rcases h.sequenceBadFace_ok with ⟨_hface, hcover⟩",
            "  exact TopPairingStrengthenedClosedLanguageAtRank.ofComponents",
            "    h.closed h.actualFaceOmni",
            "    (selectedPrefixTraceMarginSequenceBadFace_of_selectedPrefixCoverFamily hcover)",
            "",
            "theorem evalLanguage_of_strengthenedSelectedPrefixCover_viaTraceMargin",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (h :",
            "      TopPairingStrengthenedClosedLanguageAtRank",
            "        (SelectedPrefixCoverSequenceBadFace scaledMargin) rank Face.ym) :",
            "    TopPairingBellmanEvalLanguageAtRank",
            "      graphPotential graphSmokeNext smokeLabelOfFace rootState (176 : Int)",
            "      scaledMargin rank Face.ym :=",
            "  evalLanguage_of_strengthenedSelectedPrefixTraceMargin",
            "    (strengthenedTraceMargin_of_strengthenedSelectedPrefixCover h)",
            "",
            "theorem strengthenedSelectedPrefixCover_scaledMargin_nonpos_viaTraceMargin",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (h :",
            "      TopPairingStrengthenedClosedLanguageAtRank",
            "        (SelectedPrefixCoverSequenceBadFace scaledMargin) rank Face.ym) :",
            "    scaledMargin rank <= 0 :=",
            "  strengthenedSelectedPrefixTraceMargin_scaledMargin_nonpos",
            "    (strengthenedTraceMargin_of_strengthenedSelectedPrefixCover h)",
            "",
            "theorem selected_prefix_trace_margin_cover_bridge_builds : True := by",
            "  exact True.intro",
            "",
            "end Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginCoverBridge",
            "",
        ]
    )
    return "\n".join(lines)


def render_markdown(report: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Top-Pairing Selected Prefix Trace-Margin Cover Bridge",
            "",
            "This generated bridge maps the existing selected-prefix cover family",
            "into the newer selected-prefix trace-margin socket.",
            "",
            f"- source cover: `{report['source_cover']}`",
            f"- bucket count: `{report['bucket_count']}`",
            f"- group count: `{report['group_count']}`",
            f"- Lean file: `{report['lean_file']}`",
            "",
            "The bridge introduces no sampled rank/path objects.",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cover-json", type=Path, default=DEFAULT_COVER)
    parser.add_argument("--lean", type=Path, default=DEFAULT_LEAN)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MD)
    args = parser.parse_args()

    cover = json.loads(args.cover_json.read_text())
    report = {
        "source_cover": args.cover_json.relative_to(ROOT).as_posix(),
        "bucket_count": int(cover["bucket_count"]),
        "group_count": int(cover["group_count"]),
        "groups": cover["groups"],
        "lean_file": args.lean.relative_to(ROOT).as_posix(),
    }

    args.lean.parent.mkdir(parents=True, exist_ok=True)
    args.lean.write_text(render_lean(report))
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    args.markdown.write_text(render_markdown(report))


if __name__ == "__main__":
    main()
