#!/usr/bin/env python3
"""Emit a direct selected-prefix start-violation killed bridge.

The selected-prefix cover already gives semantic terminal prefix buckets.  This
bridge maps those buckets directly to `Coverage.NonIdentityRankKilled` through
the accepted trace-id start-violation providers, bypassing the Bellman
nonpositive-margin theorem.  The input family still comes from the existing
selected-prefix cover, but the generated proofs ignore its `scaledMargin` field.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_COVER = ROOT / "scripts/generated/top_pairing_state_dag_selected_prefix_cover.json"
DEFAULT_LEAN = (
    ROOT
    / "Cuboctahedron/Generated/NonIdentity/Residual/"
    / "BellmanTopPairingSelectedPrefixDirectStartViolationKilledBridge.lean"
)
DEFAULT_JSON = (
    ROOT
    / "scripts/generated/"
    / "top_pairing_selected_prefix_direct_start_violation_killed_bridge.json"
)
DEFAULT_MD = (
    ROOT
    / "scripts/generated/"
    / "top_pairing_selected_prefix_direct_start_violation_killed_bridge.md"
)


def group_name(group_idx: int) -> str:
    return f"Group{group_idx:03d}"


def prefix_name(local_idx: int) -> str:
    return f"Prefix{local_idx:03d}"


def render_prefix_theorem(gname: str, pname: str) -> list[str]:
    return [
        f"theorem nonIdentityRankKilled_of_{gname}_{pname}ShardFamily",
        "    {scaledMargin : Fin numPairWords -> Int}",
        "    {rank : Fin numPairWords}",
        f"    (hrank : {gname}.{pname}ShardFamily scaledMargin rank) :",
        "    Cuboctahedron.Generated.Coverage.NonIdentityRankKilled rank := by",
        "  apply",
        "    nonIdentityRankKilled_of_terminalTracePrefixStartViolationFamily",
        f"      (allowedTraceId := {gname}.{pname}Allowed)",
        f"      (pfx := {gname}.{pname}Prefix)",
        f"      (fun traceId hprefix => ({gname}.{pname}Prefix_gain traceId hprefix).1)",
        "  rcases hrank with",
        "    ⟨hclosed, hactual, hbad, hterminal, hprefix, _hmargin⟩",
        "  rcases hprefix with ⟨rest, hlabels⟩",
        "  refine ⟨hclosed, hactual, hbad, hterminal, ?_⟩",
        "  rw [hlabels]",
        f"  simp [{gname}.{pname}Prefix]",
        "",
    ]


def render_lean(report: dict[str, Any]) -> str:
    groups = list(report["groups"])
    lines: list[str] = [
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTraceStartViolationDirectKilledBridge",
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingStateDAGSelectedPrefixCover.All",
        "",
        "/-!",
        "Direct killed bridge for the bounded selected-prefix top-pairing cover.",
        "",
        "Generated by",
        "`scripts/emit_top_pairing_selected_prefix_direct_start_violation_killed_bridge.py`.",
        "",
        "The selected-prefix cover is semantic and contains no sampled rank/path",
        "objects.  This bridge bypasses the Bellman nonpositive-margin theorem:",
        "each selected terminal prefix determines an accepted trace-id bucket,",
        "and the all-trace start-violation providers kill the nonidentity rank",
        "directly.",
        "-/",
        "",
        "set_option maxHeartbeats 2000000",
        "set_option maxRecDepth 4096",
        "",
        "namespace Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixDirectStartViolationKilledBridge",
        "",
        "open Cuboctahedron",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTraceStartViolationDirectKilledBridge",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingStateDAGSelectedPrefixCover",
        "",
    ]

    for group in groups:
        gidx = int(group["index"])
        gname = group_name(gidx)
        start = int(group["bucket_start"])
        end = int(group["bucket_end"])
        for global_idx in range(start, end):
            local_idx = global_idx - start
            lines.extend(render_prefix_theorem(gname, prefix_name(local_idx)))

        local_count = end - start
        lines.extend(
            [
                f"theorem nonIdentityRankKilled_of_{gname}SelectedPrefixGroupFamily",
                "    {scaledMargin : Fin numPairWords -> Int}",
                "    {rank : Fin numPairWords}",
                f"    (hrank : {gname}.SelectedPrefixGroupFamily scaledMargin rank) :",
                "    Cuboctahedron.Generated.Coverage.NonIdentityRankKilled rank := by",
                f"  unfold {gname}.SelectedPrefixGroupFamily at hrank",
            ]
        )
        if local_count == 1:
            lines.append(
                f"  exact nonIdentityRankKilled_of_{gname}_Prefix000ShardFamily hrank"
            )
        else:
            lines.append(
                "  rcases hrank with "
                + " | ".join(f"h{i}" for i in range(local_count))
            )
            for local_idx in range(local_count):
                pname = prefix_name(local_idx)
                lines.append(
                    f"  · exact nonIdentityRankKilled_of_{gname}_{pname}ShardFamily h{local_idx}"
                )
        lines.append("")

    lines.extend(
        [
            "theorem nonIdentityRankKilled_of_selectedPrefixCoverFamily",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixCoverFamily scaledMargin rank) :",
            "    Cuboctahedron.Generated.Coverage.NonIdentityRankKilled rank := by",
            "  unfold SelectedPrefixCoverFamily at hrank",
            "  rcases hrank with "
            + " | ".join(f"h{i}" for i in range(len(groups))),
        ]
    )
    for group in groups:
        gidx = int(group["index"])
        gname = group_name(gidx)
        lines.append(
            f"  · exact nonIdentityRankKilled_of_{gname}SelectedPrefixGroupFamily h{gidx}"
        )
    lines.extend(
        [
            "",
            "theorem selected_prefix_direct_start_violation_killed_bridge_builds : True := by",
            "  exact True.intro",
            "",
            "end Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixDirectStartViolationKilledBridge",
            "",
        ]
    )
    return "\n".join(lines)


def render_markdown(report: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Top-Pairing Selected Prefix Direct Start-Violation Killed Bridge",
            "",
            "This generated bridge maps the bounded selected-prefix cover family",
            "directly to `Coverage.NonIdentityRankKilled` using accepted trace-id",
            "start-violation providers.  The bridge does not use sampled objects",
            "or the Bellman nonpositive-margin theorem.",
            "",
            f"- source cover: `{report['source_cover']}`",
            f"- bucket count: `{report['bucket_count']}`",
            f"- group count: `{report['group_count']}`",
            f"- Lean file: `{report['lean_file']}`",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cover-json", type=Path, default=DEFAULT_COVER)
    parser.add_argument("--lean", type=Path, default=DEFAULT_LEAN)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MD)
    args = parser.parse_args()

    cover = json.loads(args.cover_json.read_text())
    args.lean.parent.mkdir(parents=True, exist_ok=True)
    args.lean.write_text(render_lean(cover))

    report = {
        "source_cover": args.cover_json.relative_to(ROOT).as_posix(),
        "bucket_count": int(cover["bucket_count"]),
        "group_count": int(cover["group_count"]),
        "lean_file": args.lean.relative_to(ROOT).as_posix(),
        "groups": cover["groups"],
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    args.markdown.write_text(render_markdown(report))


if __name__ == "__main__":
    main()
