#!/usr/bin/env python3
"""Emit a semantic adapter from trace-margin prefix families to the cover.

The selected-prefix cover uses explicit prefix/tail witnesses.  The older
trace-margin socket exposes the same prefix/gain idea with a `take` predicate.
This generated adapter proves the conversion for every selected prefix bucket,
then exposes a single disjunctive family surface.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_COVER = ROOT / "scripts/generated/top_pairing_shared_gain_prefix_cover_plan.json"
DEFAULT_LEAN = (
    ROOT
    / "Cuboctahedron/Generated/NonIdentity/Residual/"
    / "BellmanTopPairingSelectedPrefixTraceMarginAdapter.lean"
)
DEFAULT_JSON = (
    ROOT / "scripts/generated/top_pairing_selected_prefix_trace_margin_adapter.json"
)
DEFAULT_MD = (
    ROOT / "scripts/generated/top_pairing_selected_prefix_trace_margin_adapter.md"
)


def group_name(bucket_idx: int) -> str:
    return f"Group{bucket_idx // 5:03d}"


def prefix_name(bucket_idx: int) -> str:
    return f"Prefix{bucket_idx % 5:03d}"


def nested_or_type(terms: list[str]) -> str:
    if len(terms) == 1:
        return terms[0]
    return " \\/\n    ".join(terms)


def nested_or_wrap(index: int, count: int, proof: str) -> str:
    if count == 1:
        return proof
    if index == 0:
        return f"Or.inl ({proof})"
    return f"Or.inr ({nested_or_wrap(index - 1, count - 1, proof)})"


def render_lean(cover: dict[str, Any]) -> str:
    buckets = list(cover["cover"])
    group_count = (len(buckets) + 4) // 5
    family_terms = []
    for idx, bucket in enumerate(buckets):
        group = group_name(idx)
        prefix = prefix_name(idx)
        gain = int(bucket["gain"])
        family_terms.append(
            "Cuboctahedron.Generated.NonIdentity.Residual."
            "BellmanTopPairingTraceMarginBoundsSocket."
            "TerminalTracePrefixSharedGainClosedMarginFamily "
            f"{group}.{prefix}Prefix ({gain} : Int) scaledMargin rank"
        )

    lines = [
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingStateDAGSelectedPrefixCover.All",
        "import Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTraceMarginBoundsSocket",
        "",
        "/-!",
        "Adapter from trace-margin prefix/gain families into the selected-prefix cover.",
        "",
        "Generated by",
        "`scripts/emit_top_pairing_selected_prefix_trace_margin_adapter.py`.",
        "No sampled rank/path objects are introduced.",
        "-/",
        "",
        "namespace Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginAdapter",
        "",
        "open Cuboctahedron",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingGraphEvalSplit10MSmoke.Base",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingStateDAGSelectedPrefixCover",
        "open Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingTraceMarginBoundsSocket",
        "",
        "private theorem exists_rest_of_take_eq",
        "    {labels pfx : List Face}",
        "    (h : labels.take pfx.length = pfx) :",
        "    ∃ rest : List Face, labels = pfx ++ rest := by",
        "  refine ⟨labels.drop pfx.length, ?_⟩",
        "  calc",
        "    labels = labels.take pfx.length ++ labels.drop pfx.length := by",
        "      exact (List.take_append_drop pfx.length labels).symm",
        "    _ = pfx ++ labels.drop pfx.length := by",
        "      rw [h]",
        "",
        "def SelectedPrefixTraceMarginFamily",
        "    (scaledMargin : Fin numPairWords -> Int)",
        "    (rank : Fin numPairWords) : Prop :=",
        "  " + nested_or_type(family_terms),
        "",
    ]

    for idx, bucket in enumerate(buckets):
        group = group_name(idx)
        prefix = prefix_name(idx)
        gain = int(bucket["gain"])
        bucket_count = min(5, len(buckets) - (idx // 5) * 5)
        local_idx = idx % 5
        hshard = (
            f"⟨hclosed, hactual, hbad, hterminal, hrest, hmargin⟩"
        )
        hgroup = nested_or_wrap(local_idx, bucket_count, hshard)
        hcover = nested_or_wrap(idx // 5, group_count, hgroup)
        lines.extend(
            [
                f"theorem selectedPrefixCoverFamily_of_terminalPrefix_{idx:03d}",
                "    {scaledMargin : Fin numPairWords -> Int}",
                "    {rank : Fin numPairWords}",
                "    (hrank :",
                "      TerminalTracePrefixSharedGainClosedMarginFamily",
                f"        {group}.{prefix}Prefix ({gain} : Int) scaledMargin rank) :",
                "    SelectedPrefixCoverFamily scaledMargin rank := by",
                "  rcases hrank with",
                "    ⟨hclosed, hactual, hbad, hterminal, hprefix, hmargin⟩",
                "  have hrest :",
                f"      ∃ rest : List Face, topPairingRankFaceLabels rank = {group}.{prefix}Prefix ++ rest :=",
                "    exists_rest_of_take_eq hprefix",
                f"  exact {hcover}",
                "",
            ]
        )

    lines.extend(
        [
            "theorem selectedPrefixCoverFamily_of_traceMarginFamily",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixTraceMarginFamily scaledMargin rank) :",
            "    SelectedPrefixCoverFamily scaledMargin rank := by",
            "  unfold SelectedPrefixTraceMarginFamily at hrank",
            "  rcases hrank with "
            + " | ".join(f"h{i}" for i in range(len(buckets))),
        ]
    )
    for idx in range(len(buckets)):
        lines.append(
            f"  · exact selectedPrefixCoverFamily_of_terminalPrefix_{idx:03d} h{idx}"
        )

    lines.extend(
        [
            "",
            "theorem selectedPrefixTraceMarginFamily_evalLanguage",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixTraceMarginFamily scaledMargin rank) :",
            "    TopPairingBellmanEvalLanguageAtRank",
            "      graphPotential graphSmokeNext smokeLabelOfFace rootState (176 : Int)",
            "      scaledMargin rank Face.ym :=",
            "  selectedPrefixCover_evalLanguage",
            "    (selectedPrefixCoverFamily_of_traceMarginFamily hrank)",
            "",
            "theorem selectedPrefixTraceMarginFamily_scaledMargin_nonpos",
            "    {scaledMargin : Fin numPairWords -> Int}",
            "    {rank : Fin numPairWords}",
            "    (hrank : SelectedPrefixTraceMarginFamily scaledMargin rank) :",
            "    scaledMargin rank <= 0 :=",
            "  selectedPrefixCover_scaledMargin_nonpos",
            "    (selectedPrefixCoverFamily_of_traceMarginFamily hrank)",
            "",
            "theorem selected_prefix_trace_margin_adapter_builds : True := by",
            "  exact True.intro",
            "",
            "end Cuboctahedron.Generated.NonIdentity.Residual.BellmanTopPairingSelectedPrefixTraceMarginAdapter",
            "",
        ]
    )
    return "\n".join(lines)


def render_markdown(report: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Top-Pairing Selected Prefix Trace-Margin Adapter",
            "",
            "This generated adapter maps trace-margin prefix/gain families into",
            "the selected-prefix cover family.",
            "",
            f"- source cover: `{report['source_cover']}`",
            f"- prefix buckets: `{report['bucket_count']}`",
            f"- Lean file: `{report['lean_file']}`",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cover-json", type=Path, default=DEFAULT_COVER)
    parser.add_argument("--lean", type=Path, default=DEFAULT_LEAN)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MD)
    args = parser.parse_args()

    cover = json.loads(args.cover_json.read_text())
    args.lean.parent.mkdir(parents=True, exist_ok=True)
    args.lean.write_text(render_lean(cover))

    report = {
        "source_cover": args.cover_json.relative_to(ROOT).as_posix(),
        "bucket_count": len(cover["cover"]),
        "lean_file": args.lean.relative_to(ROOT).as_posix(),
    }
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    args.markdown.write_text(render_markdown(report))


if __name__ == "__main__":
    main()
