#!/usr/bin/env python3
"""Generate AP.16BP all-selected-subcube Walsh-bound smoke.

This scales the AP16BO one-subcube emitter to all AP16BJ selected subcubes for
rank 100805.  It still proves only polynomial nonpositivity; the bridge from
`impactDenomAtRank` to these Walsh polynomials remains a separate task.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from generate_ap16bo_walsh_bound_smoke import (  # noqa: E402
    DEFAULT_PROFILE,
    DEFAULT_RANK,
    DEFAULT_MASK,
    DEFAULT_SELECTED,
    emit_cube,
    emit_fixed_theorems,
    emit_poly,
    emit_upper,
    fraction_to_text,
    selected_data,
)


DEFAULT_LEAN = Path(
    "Cuboctahedron/Generated/Translation/TwoSource/SupportFamilies/"
    "ImpactSubcubeWalshAllSmoke.lean"
)
DEFAULT_REPORT = Path(
    "scripts/generated/phase6z6k8ap16bp_walsh_bound_all_smoke.json"
)


def emit_block(data: dict, namespace_name: str) -> list[str]:
    selected = data["selected"]
    lines = [
        "",
        f"namespace {namespace_name}",
        "",
        f"-- rank {data['rank']}, selected subcube {data['selected_index']}, "
        f"label {selected['label']}, impact {selected['impact']}",
    ]
    lines.extend(emit_cube(selected["label"]))
    lines.append("")
    lines.extend(emit_poly(data["terms"]))
    lines.extend(emit_fixed_theorems(selected["label"]))
    lines.append("")
    lines.extend(emit_upper(data))
    lines.extend([
        "",
        "theorem generatedPoly_nonpos",
        "    {mask : SignMask} (hmask : generatedCube.Member mask) :",
        "    generatedPoly.eval mask <= 0 :=",
        "  generatedUpper.eval_nonpos hmask",
        "",
        f"end {namespace_name}",
    ])
    return lines


def emit_lean(all_data: list[dict]) -> str:
    lines = [
        "import Cuboctahedron.Generated.Translation.TwoSource.SupportFamilies.ImpactSubcubeWalsh",
        "",
        "/-!",
        "Generated AP.16BP all-selected-subcube Walsh-bound smoke.",
        "",
        "This file is generated by `scripts/generate_ap16bp_walsh_bound_all_smoke.py`.",
        "It proves polynomial nonpositivity for all AP16BJ selected subcubes for",
        "rank 100805, without per-mask nonpositivity replay.",
        "-/",
        "",
        "namespace Cuboctahedron.Generated.Translation.TwoSource.SupportFamilies.ImpactSubcubeWalshAllSmoke",
        "",
        "open Cuboctahedron.Generated.Translation.TwoSource.SupportFamilies.PositiveSurvivorClassifier",
        "open Cuboctahedron.Generated.Translation.TwoSource.SupportFamilies.PositiveSurvivorClassifier.ImpactSubcube",
        "",
        "private def constMonomial : WalshMonomial :=",
        "  { fst := none, snd := none }",
        "",
        "private def bitMonomial (bit : SignBit) : WalshMonomial :=",
        "  { fst := some bit, snd := none }",
        "",
        "private def twoBitMonomial (fst snd : SignBit) : WalshMonomial :=",
        "  { fst := some fst, snd := some snd }",
    ]
    for data in all_data:
        lines.extend(emit_block(data, f"Subcube{data['selected_index']:03d}"))
    lines.extend([
        "",
        "theorem impactSubcubeWalshAllSmoke_builds : True := by",
        "  trivial",
        "",
        "end Cuboctahedron.Generated.Translation.TwoSource.SupportFamilies.ImpactSubcubeWalshAllSmoke",
    ])
    return "\n".join(lines) + "\n"


def write_report(all_data: list[dict], report_path: Path, lean_path: Path) -> None:
    report = {
        "phase": "Phase 6Z.6K.8AP.16BP",
        "status": "generated_pending_build",
        "rank": all_data[0]["rank"] if all_data else DEFAULT_RANK,
        "selected_count": len(all_data),
        "total_terms": sum(len(data["terms"]) for data in all_data),
        "max_terms": max((len(data["terms"]) for data in all_data), default=0),
        "max_degree": max(
            (len(subset) for data in all_data for subset, _coeff in data["terms"]),
            default=0,
        ),
        "lean_file": str(lean_path),
        "connects_to_impactDenomAtRank": False,
        "trusted_as_final_generated_coverage": False,
        "subcubes": [
            {
                "selected_index": data["selected_index"],
                "label": data["selected"]["label"],
                "impact": data["selected"]["impact"],
                "term_count": len(data["terms"]),
                "bound_sum": fraction_to_text(data["bound_sum"]),
            }
            for data in all_data
        ],
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    md_lines = [
        "# Phase 6Z.6K.8AP.16BP Walsh Bound All-Subcube Smoke",
        "",
        "Status: generated; focused Lean build required for acceptance.",
        "",
        f"- rank: `{report['rank']}`",
        f"- selected subcubes: `{report['selected_count']}`",
        f"- total terms: `{report['total_terms']}`",
        f"- max terms per subcube: `{report['max_terms']}`",
        f"- max Walsh degree: `{report['max_degree']}`",
        "",
        "| index | label | impact | terms | bound sum |",
        "| ---: | --- | ---: | ---: | ---: |",
    ]
    for subcube in report["subcubes"]:
        md_lines.append(
            f"| {subcube['selected_index']} | `{subcube['label']}` | "
            f"{subcube['impact']} | {subcube['term_count']} | "
            f"`{subcube['bound_sum']}` |"
        )
    md_lines.extend([
        "",
        "This generated smoke proves polynomial nonpositivity through",
        "`WalshSubcubeUpperBound`; it does not yet prove equality with",
        "`impactDenomAtRank`.",
        "",
    ])
    report_path.with_suffix(".md").write_text("\n".join(md_lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", type=Path, default=DEFAULT_PROFILE)
    parser.add_argument("--selected", type=Path, default=DEFAULT_SELECTED)
    parser.add_argument("--rank", type=int, default=DEFAULT_RANK)
    parser.add_argument("--mask", type=int, default=DEFAULT_MASK)
    parser.add_argument("--lean-output", type=Path, default=DEFAULT_LEAN)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    args = parser.parse_args()

    selected_profile = json.loads(args.selected.read_text(encoding="utf-8"))
    all_data = [
        selected_data(args.profile, args.selected, args.rank, args.mask, index)
        for index in range(len(selected_profile["selected"]))
    ]
    args.lean_output.parent.mkdir(parents=True, exist_ok=True)
    args.lean_output.write_text(emit_lean(all_data), encoding="utf-8")
    write_report(all_data, args.report, args.lean_output)
    print(
        f"wrote {args.lean_output}; subcubes={len(all_data)} "
        f"terms={sum(len(data['terms']) for data in all_data)}"
    )


if __name__ == "__main__":
    main()
